services:
  db:
    image: postgres:latest
    container_name: game_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  app:
    build: .
    container_name: xoplay_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data: