name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake clang-format libpqxx-dev libboost-system-dev libcurl4-openssl-dev libssl-dev zlib1g-dev

      - name: Run clang-format check
        run: |
          find . -name "*.cpp" -o -name "*.h" -print0 | xargs -0 clang-format --dry-run --Werror

      - name: Configure, build and test
        run: |
          rm -rf build
          mkdir build && cd build
          cmake ..
          cmake --build . -- -j$(nproc)
          ctest --output-on-failure